### ISSUE TITLE
你好，感谢您的分享

### ISSUE THREAD

**Issue by zhanghongruiupup** [wangguanan/light-reid#12]
feature dim的multiple指的是什么呢？

以及表格最后一列的搜索耗时是否使用了faiss？

**Comment by wangguanan** [comment]
1. 你好，multiple 指的是使用多种不同的长度特征进行 coarse2fine search。
我们使用了 {2048, 512, 128, 32} 4种不同长度的编码，具体算法请参考我们ECCV2020的paper。
https://arxiv.org/abs/2008.06826


2. 目前我们没有使用 faiss，后面我们会支持。谢谢。
