### ISSUE TITLE
No return_time argument

### ISSUE THREAD

**Issue by 13331112522** [wangguanan/light-reid#14]
lightreid.evaluation

mAP, CMC, ranktime, evaltime = CmcMapEvaluatorC2F(metric=metric, mode='inter-camera').compute(
TypeError: compute() got an unexpected keyword argument 'return_time'

There's no return_time in the compute() function in  rank1b1 and rankc2f but engine uses the parameter. Plz fix it.

**Comment by wangguanan** [comment]
Thanks for your notification, I will fix it ASAP

**Comment by wangguanan** [comment]
the bug has been fixed, please re-pull the repo, thanks.
