### ISSUE TITLE
Pretrained models 

### ISSUE THREAD

**Issue by volodymyrkepsha** [wangguanan/light-reid#18]
Hi, thanks for your work. I have a question.
Are some pre-trained models available or will be available soon ?

**Comment by wangguanan** [comment]
sure, will provide some trained models soon.

**Comment by wangguanan** [comment]
Hi, please refer https://github.com/wangguanan/light-reid/tree/master/examples/model_zoo
for some pre-trained model

this project will be kept updating for more models

**Comment by kadirbeytorun** [comment]
Hey @wangguanan , 

Can you provide inference time information about the models? Since your repository is name "light", inference speed is as important as precision I think.

**Comment by wangguanan** [comment]
sure, will do
