### ISSUE TITLE
Questions about "Distance Threshold Optimization"

### ISSUE THREAD

**Issue by linjiawen2019** [wangguanan/light-reid#19]
Hi @wangguanan ,  非常感谢您的faster re-id工作，在理解论文的过程中，关于Distance Threshold Optimization算法有一些疑问：
1. 请问DTO算法中，为什么选择用高斯累计分布函数来代替precision和recall呢？
2. 论文的Eq.8 ，即Fβ的公式看的不太懂，请问该公式是如何得到的
请问关于这个算法有什么参考文献或有助于理解的出处吗？您的回答会对我有很大的帮助，感谢！

**Comment by wangguanan** [comment]
1. 因为可视化 precision 和 recall 发现，高斯累计分布函数的曲线和它比较像，所以就选择了 高斯。
2. 把公式7(右)带入公式6(右)，就可以得到公式(8)。
