### ISSUE TITLE
你好！可以提供一个在DukeMTMC-reID数据集上测试准确率的脚本么？

### ISSUE THREAD

**Issue by 205418367** [wangguanan/light-reid#20]

**Comment by wangguanan** [comment]
你好。
请参考这个project，运行直接训练+测试。
https://github.com/wangguanan/light-reid/tree/master/examples/bagtricks_buildwithconfigs

具体测试脚本（代码）请参考：https://github.com/wangguanan/light-reid/blob/master/lightreid/evaluations/rank/rank.py
这个测试代码对于 所有 reid 数据集都通用。

**Comment by 205418367** [comment]
谢谢！
