### ISSUE TITLE
我在测试的时候发现一些问题

### ISSUE THREAD

**Issue by 205418367** [wangguanan/light-reid#21]
我在测试的时候发现从pytorch下载模型，这个模型是作什么用的？

**Comment by wangguanan** [comment]
可能是 resnet50 自动下载 imagenet-pretrained model。

如果是训练阶段，下载 imagenet-pretrained model 是必须的，因为 resnet50 需要先用这个模型初始化，然后再用 reid 数据进行训练。

如果不做训练，只做推理，是不需要下载 image-pretrained model的，只需要加载 自己 reid数据训练好的模型即可。
（我后面修复这个bug，不过这个bug不影响速度和精度，就是第一次下载需要费时间和流量而已，而且只需要下载一次。）

**Comment by 205418367** [comment]
在推理过程中会下载image-pretrained model，而且不指定自己的模型，代码也不会出错

**Comment by 205418367** [comment]
我希望你可以简化测试代码，用1～2个py文件就可以实现模型推理和测试，这样方便初学者学习和c++实现用与实际工程中

**Comment by wangguanan** [comment]
感谢你宝贵的意见，我会尽快完善，敬请期待。
