### ISSUE TITLE
增加类别后的推理时间增加问题？

### ISSUE THREAD

**Issue by soolone** [wangguanan/light-reid#22]
您好，我使用您的代码训练自己数据进行训练时增加了类别，但对应的推理时间也程近似的线性增加，而且推理时间增加在backbone的推理过程，请问下是什么原因呢？能否有解决的方法？

**Comment by soolone** [comment]
例如我backbone为resnet18，训练集采用duke时类别702，CPU特征提取时间为60ms左右，采用duke+market1501混合训练时，类别为702+750，单张特征提取时间约为110ms

**Comment by wangguanan** [comment]
你好，请该是inference的时候，classifier 层没有去掉，仍然进行了计算，所以变慢了。

 

新版本中代码已经修复了，可以重新clone试一下。


如 80 行所示，如果不在训练模式（not training），直接 return feature，不计算 classifier。
https://github.com/wangguanan/light-reid/blob/master/lightreid/models/heads/bn_head.py


如果新代码仍有问题，请告诉我，我再去看看。

 

谢谢。




 

发件人: soolone <notifications@github.com>
答复: wangguanan/light-reid <reply@reply.github.com>
日期: 2020年12月24日 星期四 下午2:59
收件人: wangguanan/light-reid <light-reid@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangguanan/light-reid] 增加类别后的推理时间增加问题？ (#22)

 

您好，我使用您的代码训练自己数据进行训练时增加了类别，但对应的推理时间也程近似的线性增加，而且推理时间增加在backbone的推理过程，请问下是什么原因呢？能否有解决的方法？
