### ISSUE TITLE
BNHead中降维报错

### ISSUE THREAD

**Issue by yukaizhou** [wangguanan/light-reid#23]
Traceback (most recent call last):
  File "examples/stronger_baseline/main.py", line 77, in <module>
    margin=0.35))
  File "/dahuafs/userdata/233540/workdir/light-reid/lightreid/models/heads/bn_head.py", line 49, in __init__
    classifier['in_dim'] = in_dim if middle_dim is None else middle_dim
TypeError: 'Circle' object does not support item assignment

期待您的回复！

**Comment by gongyan1** [comment]
我运行起来了，把输出那里改一下，head = lightreid.models.BNHead(backbone.dim, class_num=datamanager.class_num)

**Comment by wangguanan** [comment]
请参考这个 project ，谢谢
https://github.com/wangguanan/light-reid/tree/master/examples/bagtricks_pca

**Comment by wangguanan** [comment]
请参考这个 project ，谢谢
https://github.com/wangguanan/light-reid/tree/master/examples/bagtricks_pca
