### ISSUE TITLE
通用reid (非仅遮挡）

### ISSUE THREAD

**Issue by sky186** [wangguanan/light-reid#25]
您好作者，
       谢谢您的工作^^, 这里有个问题请教您，您的实验结果主要是在遮挡问题的描述， 您觉得在通用问题上用您的方式，可以又更好的模型性能吗？您做过相关实验吗？

**Comment by wangguanan** [comment]
做过的，可以做到不怎么掉点。可以去看看我的 paper HONet 那一篇。
