### ISSUE TITLE
运行lightmodels时出错

### ISSUE THREAD

**Issue by cxh1996** [wangguanan/light-reid#27]
运行python train.py --config_file ./configs/base_config_duke_res18_lightmodel.yaml时出错

**Comment by cxh1996** [comment]
(lightreid) ➜  bagtricks_buildwithconfigs git:(master) ✗ python train.py --config_file ./configs/base_config_duke_res18_lightmodel.yaml

    building training datasets ... ... 
    
+--------------+--------+------------+---------+---------+----------+-------------+
| DukeMTMCreID | images | identities | cameras | imgs/id | imgs/cam | imgs/id&cam |
+--------------+--------+------------+---------+---------+----------+-------------+
|    train     | 16522  |    702     |    8    |  23.54  | 2065.25  |     2.94    |
|    query     |  2228  |    702     |    8    |   3.17  |  278.5   |     0.4     |
|   gallery    | 17661  |    1110    |    8    |  15.91  | 2207.62  |     1.99    |
+--------------+--------+------------+---------+---------+----------+-------------+

    building test datasets ... ... 
    
+------------+--------+------------+---------+---------+----------+-------------+
| Market1501 | images | identities | cameras | imgs/id | imgs/cam | imgs/id&cam |
+------------+--------+------------+---------+---------+----------+-------------+
|   train    | 12936  |    751     |    6    |  17.23  |  2156.0  |     2.87    |
|   query    |  3368  |    750     |    6    |   4.49  |  561.33  |     0.75    |
|  gallery   | 19732  |    752     |    6    |  26.24  | 3288.67  |     4.37    |
+------------+--------+------------+---------+---------+----------+-------------+
+--------------+--------+------------+---------+---------+----------+-------------+
| DukeMTMCreID | images | identities | cameras | imgs/id | imgs/cam | imgs/id&cam |
+--------------+--------+------------+---------+---------+----------+-------------+
|    train     | 16522  |    702     |    8    |  23.54  | 2065.25  |     2.94    |
|    query     |  2228  |    702     |    8    |   3.17  |  278.5   |     0.4     |
|   gallery    | 17661  |    1110    |    8    |  15.91  | 2207.62  |     1.99    |
+--------------+--------+------------+---------+---------+----------+-------------+
set mean [0.485, 0.456, 0.406]
set std [0.229, 0.224, 0.225]
set mean [0.485, 0.456, 0.406]
set std [0.229, 0.224, 0.225]
/environment/python/versions/miniconda3-4.7.12/envs/lightreid/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
cosine inter-camera

******************** light-reid settings ******************** 
light_model:  True 
light_feat:  False 
light_search:  False 
******************** light-reid settings ********************
 
[light_model was enabled] load teacher model from /home/featurize/fei/light-reid/examples/bagtricks_buildwithconfigs/results/duke/resnet50/lightmodel(False)-lightfeat(False)-lightsearch(False)/final_model.pth.tar 
[light_model was enabled] add KLLoss for model distillation 
2021-03-08 06:05:59 restore from ./results/duke/resnet18_distill/lightmodel(True)-lightfeat(False)-lightsearch(False)/model_0.pth 
[Feature Extraction] feature extraction time per batch (64) is 0.01895326079584617s 
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    solver.train(eval_freq=10)
  File "../../lightreid/engine/engine.py", line 208, in train
    self.eval(onebyone=False)
  File "../../lightreid/engine/engine.py", line 280, in eval
    mAP, CMC = self.evaluator.evaluate(
AttributeError: 'CleanEngine' object has no attribute 'evaluator'

**Comment by CynicalHeart** [comment]
> (lightreid) ➜ bagtricks_buildwithconfigs git:(master) ✗ python train.py --config_file ./configs/base_config_duke_res18_lightmodel.yaml
> 
> ```
> building training datasets ... ... 
> ```
> 
> +--------------+--------+------------+---------+---------+----------+-------------+
> | DukeMTMCreID | images | identities | cameras | imgs/id | imgs/cam | imgs/id&cam |
> +--------------+--------+------------+---------+---------+----------+-------------+
> | train | 16522 | 702 | 8 | 23.54 | 2065.25 | 2.94 |
> | query | 2228 | 702 | 8 | 3.17 | 278.5 | 0.4 |
> | gallery | 17661 | 1110 | 8 | 15.91 | 2207.62 | 1.99 |
> +--------------+--------+------------+---------+---------+----------+-------------+
> 
> ```
> building test datasets ... ... 
> ```
> 
> +------------+--------+------------+---------+---------+----------+-------------+
> | Market1501 | images | identities | cameras | imgs/id | imgs/cam | imgs/id&cam |
> +------------+--------+------------+---------+---------+----------+-------------+
> | train | 12936 | 751 | 6 | 17.23 | 2156.0 | 2.87 |
> | query | 3368 | 750 | 6 | 4.49 | 561.33 | 0.75 |
> | gallery | 19732 | 752 | 6 | 26.24 | 3288.67 | 4.37 |
> +------------+--------+------------+---------+---------+----------+-------------+
> +--------------+--------+------------+---------+---------+----------+-------------+
> | DukeMTMCreID | images | identities | cameras | imgs/id | imgs/cam | imgs/id&cam |
> +--------------+--------+------------+---------+---------+----------+-------------+
> | train | 16522 | 702 | 8 | 23.54 | 2065.25 | 2.94 |
> | query | 2228 | 702 | 8 | 3.17 | 278.5 | 0.4 |
> | gallery | 17661 | 1110 | 8 | 15.91 | 2207.62 | 1.99 |
> +--------------+--------+------------+---------+---------+----------+-------------+
> set mean [0.485, 0.456, 0.406]
> set std [0.229, 0.224, 0.225]
> set mean [0.485, 0.456, 0.406]
> set std [0.229, 0.224, 0.225]
> /environment/python/versions/miniconda3-4.7.12/envs/lightreid/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
> warnings.warn(warning.format(ret))
> cosine inter-camera
> 
> ******************** light-reid settings ********************
> light_model: True
> light_feat: False
> light_search: False
> ******************** light-reid settings ********************
> 
> [light_model was enabled] load teacher model from /home/featurize/fei/light-reid/examples/bagtricks_buildwithconfigs/results/duke/resnet50/lightmodel(False)-lightfeat(False)-lightsearch(False)/final_model.pth.tar
> [light_model was enabled] add KLLoss for model distillation
> 2021-03-08 06:05:59 restore from ./results/duke/resnet18_distill/lightmodel(True)-lightfeat(False)-lightsearch(False)/model_0.pth
> [Feature Extraction] feature extraction time per batch (64) is 0.01895326079584617s
> Traceback (most recent call last):
> File "train.py", line 23, in
> solver.train(eval_freq=10)
> File "../../lightreid/engine/engine.py", line 208, in train
> self.eval(onebyone=False)
> File "../../lightreid/engine/engine.py", line 280, in eval
> mAP, CMC = self.evaluator.evaluate(
> AttributeError: 'CleanEngine' object has no attribute 'evaluator'

我也遇到了相似的问题，请问您解决了没？可以分享下经验吗。蟹蟹
