### ISSUE TITLE
About the entry script/config for the paper Faster Person Re-Identification

### ISSUE THREAD

**Issue by hsfzxjy** [wangguanan/light-reid#30]
Hi, thanks for your impressive work of _Faster Person Re-Identification_!

I would like to try training related models by myself, but could hardly find the training script or config files in this repository. Could you give me some advice?

**Comment by wangguanan** [comment]
Thanks for your attention to our work.

You can refer to here https://github.com/wangguanan/light-reid/tree/master/examples/bagtricks_buildwithconfigs

 

发件人: Xie Jingyi ***@***.***>
答复: wangguanan/light-reid ***@***.***>
日期: 2021年3月24日 星期三 下午8:00
收件人: wangguanan/light-reid ***@***.***>
抄送: Subscribed ***@***.***>
主题: [wangguanan/light-reid] About the entry script/config for the paper Faster Person Re-Identification (#30)

 

I would like to try training related models by myself, but could hardly find the training script or config files in this repository. Could you give me some advice?

**Comment by hsfzxjy** [comment]
Thanks for your reply. I will try it out.
