### ISSUE TITLE
关于哈希的问题

### ISSUE THREAD

**Issue by cxh1996** [wangguanan/light-reid#31]
对特征的二值化编码，论文中写的是通过sgn(bn(Vk)),实际我看代码里用的tanh()，为什么这种简单的二值化编码方法相比于ABC在mAP上提升那么大。

给出的表格中的search per query是指的什么，和论文中的Q.Time是一个意思吗

**Comment by wangguanan** [comment]
ABC方法没有开源代码，具体原因我也不知道。

search per query 就是 Q.Time

 

 

 

发件人: cxh1996 ***@***.***>
答复: wangguanan/light-reid ***@***.***>
日期: 2021年3月24日 星期三 下午9:13
收件人: wangguanan/light-reid ***@***.***>
抄送: Subscribed ***@***.***>
主题: [wangguanan/light-reid] 关于哈希的问题 (#31)

 

对特征的二值化编码，论文中写的是通过sgn(bn(Vk)),实际我看代码里用的tanh()，为什么这种简单的二值化编码方法相比于ABC在mAP上提升那么大。

给出的表格中的search per query是指的什么，和论文中的Q.Time是一个意思吗

**Comment by cxh1996** [comment]
感谢您的回复，您项目里具体的哈希的部分在哪里呢，

**Comment by wangguanan** [comment]
https://github.com/wangguanan/light-reid/blob/cc9f717f57075323baea450d49b9bc76d6149c33/lightreid/models/heads/bn_head.py#L108-L110

请参考这几行代码，谢谢。

**Comment by cxh1996** [comment]
ok，谢谢
