### ISSUE TITLE
Regarding some details in Faster Person Re-Identification

### ISSUE THREAD

**Issue by hsfzxjy** [wangguanan/light-reid#32]
Hi. I have some questions about the implementation of the paper _Faster Person Re-Identification_.

---
**1.** In the paper you have mentioned the loss formulation:
![image](https://user-images.githubusercontent.com/4702188/112591063-be7e5900-8e3e-11eb-8be0-0e8cf7ed0ca9.png)
I am wondering should the L_ce and L_tri be added on all the codes or just on the output of the main bnneck?

---
**2.** In the paper you have mentioned the loss formulation of self-distilation loss:
![image](https://user-images.githubusercontent.com/4702188/112593809-ff786c80-8e42-11eb-985b-e66c7153f828.png)
which use previous code outputs as soft labels to supervise latter code outputs. But in your code https://github.com/wangguanan/light-reid/blob/master/lightreid/losses/self_distill_loss.py#L27 , seems it's only using the first one as teacher. What's the difference here?

Looking forward to your feekback!

**Comment by wangguanan** [comment]
Yes，it is right

 

发件人: Xie Jingyi ***@***.***>
答复: wangguanan/light-reid ***@***.***>
日期: 2021年3月26日 星期五 下午2:24
收件人: wangguanan/light-reid ***@***.***>
抄送: Subscribed ***@***.***>
主题: [wangguanan/light-reid] About the L_ce and L_tri losses in Faster Person Re-Identification (#32)

 

Hi. In the paper Faster Person Re-Identification, you have the loss formulation:

I am wondering should the L_ce and L_tri be added on all the codes or just on the output of the main bnneck?
Looking forward to your feekback!

**Comment by wangguanan** [comment]
1. added on all the codes
2. yes, we find using the first (the longest) code as a teacher works better. but using previous code also works well.

**Comment by hsfzxjy** [comment]
Thanks for the clarification.
