### ISSUE TITLE
'CleanEngine' object has no attribute 'evaluator'

### ISSUE THREAD

**Issue by CynicalHeart** [wangguanan/light-reid#35]
### 蒸馏时出现的问题

在我完成`base_config_duke_res50.yaml`的训练后，我想使用`lightmodel`的方式蒸馏得到较好的`res18`模型，我修改了`base_config_duke_res18_lightmodel_lightfeat.yaml`中`teacher_path`的路径后开始加载训练配置，出现如下的问题：

```python
...
******************** light-reid settings ******************** 
light_model:  True 
light_feat:  True 
light_search:  False 
******************** light-reid settings ********************
 
[light_model was enabled] load teacher model from /home/rosy/MySpace/ReID/light-reid/results/duke/resnet50/lightmodel(False)-lightfeat(False)-lightsearch(False)/final_model.pth.tar 
[light_model was enabled] add KLLoss for model distillation 
[light_feat was enabled] model learn binary codes, and is evaluated with hamming distance 
[light_feat was enabled] update eval_metric from cosine to hamming by setting self.eval_metric=hamming 
[Feature Extraction] feature extraction time per batch (64) is 0.0305269001597199s 
Traceback (most recent call last):
  File "examples/bagtricks_buildwithconfigs/train.py", line 22, in <module>
    solver.train(eval_freq=10)
  File "./lightreid/engine/engine.py", line 219, in train
    self.eval(onebyone=False)
  File "./lightreid/engine/engine.py", line 290, in eval
    mAP, CMC = self.evaluator.evaluate(
AttributeError: 'CleanEngine' object has no attribute 'evaluator'
```
我想问下是哪里出了问题。

> 我训练出res50(duke)的rank-1只有`0.8658`，mAP为`0.76`，在仅仅使用bag的`trick`的情况下，这个结果稍低于了我的预期，是我训练的方式有为题吗？

**Comment by wangguanan** [comment]
你好，参考 [paper](https://arxiv.org/pdf/1903.07071.pdf)，在 duke 数据集，不使用后处理算法（重排序/re-rank），r1=86.1， map=76.4。你训练出的结果是合理的。

报错问题我去修复一下。

**Comment by CynicalHeart** [comment]
> r1=86.1， map=76.4。你训练出的结果是合理的。
> 
> 报错问题我去修复一下。

非常感谢您如此快速的回复，是我期望过高了，不做`re-ranking`分数的确会低一个档次。我会耐心等待`bug`的修复！

**Comment by wangguanan** [comment]
bug 已经修复，请参考 [commit](https://github.com/wangguanan/light-reid/commit/846b33bd941d70669279847cc5a303eac8d03d76)

**Comment by CynicalHeart** [comment]
> bug 已经修复，请参考 [commit](https://github.com/wangguanan/light-reid/commit/846b33bd941d70669279847cc5a303eac8d03d76)

已经解决问题啦，非常感谢！😉
