### ISSUE TITLE
WildTrackCrop dataset

### ISSUE THREAD

**Issue by edwardnguyen1705** [wangguanan/light-reid#40]
Dear @wangguanan 
Thanks for sharing your work.
I have tried to download the Wildtrack dataset. When I crop person images  using the information provided in the annotation_positions, I see boxes are not fitted to persons.
How do you get the WildTrackCrop? Could you share me via Googledrive?

**Comment by wangguanan** [comment]
please find the dataset here.
https://drive.google.com/file/d/1g_EfB7-t0sdN5c-RgRN8VSeZjj2ibxlV/view?usp=sharing
